//Create User Actions


//Login Actions
export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_ERROR = "AUTH_ERROR"
export const AUTH_SUCCESS = "AUTH_SUCCESS"

//Logout Actions
export const LOGOUT = "LOGOUT"


//users
export const REQUEST_USER = "REQUEST_USER"
export const SHOW_USER = "SHOW_USER"

//Users Attributes
export const REQUEST_MEDICATIONS = "REQUEST_MEDICATIONS"
export const ADD_MEDICATION = "ADD_MEDICATION"
export const UPDATE_MEDICATION = "UPDATE_MEDICATION"

export const REQUEST_INSURANCES = "REQUEST_INSURANCES"
export const ADD_INSURANCE = "ADD_INSURANCE"
export const UPDATE_INSURANCE = "UPDATE_INSURANCE"

export const REQUEST_PROVIDERS= "REQUEST_PROVIDERS"
export const ADD_PROVIDER = "ADD_PROVIDER"
export const UPDATE_PROVIDER = "UPDATE_PROVIDER"

export const REQUEST_BEHAVIORS = "REQUEST_BEHAVIORS"
export const CREATE_BEHAVIOR = "CREATE_BEHAVIORS"
export const UPDATE_BEHAVIOR = "UPDATE_BEHAVIORS"

export const REQUEST_CONDITIONS= "REQUEST_CONDITIONS"
export const ADD_CONDITION = "ADD_CONDITION"
export const UPDATE_CONDITION = "UPDATE_CONDITION"
